version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      SECRET_KEY: "dev_secret_key"
      APP_DATA_DIR: "/app_data" # Путь к данным ВНУТРИ контейнера
      FLASK_ENV: "development"
      FLASK_DEBUG: "1" # Включить дебаггер Flask
    volumes:
      - ./src:/app/src
      - ./data_dev:/app_data
    command: python /app/src/quotescom/web.py